### ISSUE TITLE
Memory Analysis Exception, Dump File is not deleted

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#101]
When encountering exception during  MEMORY analysis (particularly on volatility).
Memory dump stays on analysis directory. It will consume storage space when having many failed memory analysis.

Request: If it is ok, add an option on memory.conf to force delete the dump if analysis fails to process memory scanning. This will conserve space.

(snippets)
ERROR:modules.processing.memory:Generic error executing volatility
Traceback (most recent call last):
  File "/home/xxx/tools/cuckoo-modified/utils/../modules/processing/memory.py", line 1219, in run
    results = vol.run(manager=machine_manager, vm=task_machine)
  File "/home/xxx/tools/cuckoo-modified/utils/../modules/processing/memory.py", line 1105, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/home/xxx/tools/cuckoo-modified/utils/../modules/processing/memory.py", line 63, in **init**
    self.__config()
  File "/home/xxx/tools/cuckoo-modified/utils/../modules/processing/memory.py", line 118, in __config
    if self._get_dtb():
  File "/home/xxx/tools/cuckoo-modified/utils/../modules/processing/memory.py", line 68, in _get_dtb
    for ep in ps.calculate():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.3.1-py2.7.egg/volatility/plugins/filescan.py", line 423, in calculate
    kernel_as = utils.load_as(self._config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.3.1-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareSnapshotFile: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF64 Header signature invalid
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF64 Header signature invalid
 VMWareSnapshotFile: Invalid VMware signature: 0xf000ff53
 WindowsCrashDumpSpace32: Header signature invalid
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

--- after this, memory analysis fails. And memory dump will not be deleted on analysis directory.

**Comment by brad-sp** [comment]
Is there any case where you'd actually want to keep the file around?  I'm inclined to just always remove it for this case.

**Comment by ghost** [comment]
Please disregard the original request.
I'm ok to just delete the memory dump if encountered an error. This will isolate the modification and also prevent large storage consumption.
Thank you.

**Comment by ghost** [comment]
Hi Brad,

Do we have commit/modification for this case?

**Comment by KillerInstinct** [comment]
Personally, I'd want this to be a configuration option. There are instances (in testing code mostly) where if an error happens, I don't want to delete the dump so that I can reprocess it later. If the memory dump is deleted, the only way to get another is to run a duplicate task.

**Comment by ghost** [comment]
Thank you @seanthegeek . Im now closing this issue
