### ISSUE TITLE
Syntax error: process.py

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#125]
Line no 62
.....
                        if mdata.analysis.find({"target.file_id": ObjectId(analysis["target"]["file_id"])}).count()>
                            fs.delete(ObjectId(analysis["target"]["file_id"]))
.....

**Comment by KillerInstinct** [comment]
This fixes it: https://github.com/brad-accuvant/cuckoo-modified/pull/124
