### ISSUE TITLE
timeout when run cuckoo in macos

### ISSUE THREAD

**Issue by ZeeZerEn** [brad-accuvant/cuckoo-modified#13]
when i submit a file,vm is running,but no file copy to vm.

**Comment by brad-sp** [comment]
Did you install the agent in the guest and confirm it's running?

**Comment by ZeeZerEn** [comment]
The vm is used by original cuckoo, the conf file modified, run cuckoo.py is no error info.

**Comment by brad-sp** [comment]
Can you provide any more info on this?  I'd like to fix it, but I have no means to test or debug.
