### ISSUE TITLE
Country always "unknown"

### ISSUE THREAD

**Issue by jcannell** [brad-accuvant/cuckoo-modified#140]
Hello,

For network requests, why is it that the "Country Name" column in the reports is always "unknown"? Is there a config option that I'm missing here?

**Comment by SeanKim777** [comment]
Hi, I had same issue and fixed it with below command on Ubuntu 14.04
sudo add-apt-repository ppa:maxmind/ppa
sudo apt-get update
sudo apt-get install libgeoip1 libgeoip-dev geoip-bin
sudo pip install GeoIP

**Comment by jcannell** [comment]
Hi,

I tried installed the above packages (but not from the ppa you used, they were in the ubuntu repos). Didn't have any luck.

Is there a special requirement to get this to work, Brad?

**Comment by SeanKim777** [comment]
Have a look at this https://github.com/maxmind/geoip-api-c

**Comment by jcannell** [comment]
I took a look at it. Installed per the directions, but still isn't working for me...

**Comment by KillerInstinct** [comment]
There is a config option, but it defaults to on:

https://github.com/brad-accuvant/cuckoo-modified/blob/master/conf/cuckoo.conf#L101

**Comment by jcannell** [comment]
Yeah, that's always been on. Still doesn't work.

**Comment by brad-sp** [comment]
What's the output of python -c "import GeoIP" ?

Did you also apt-get install geoip-database ?

**Comment by jcannell** [comment]
Thank you, Brad. Works great now with geoip-database
