### ISSUE TITLE
Standalone Auto Processing not cooperating.

### ISSUE THREAD

**Issue by fulco** [brad-accuvant/cuckoo-modified#142]
I have flushed my database and even done a complete wipe and reinstall of my install and all databases involved.  If I turn the processing back on in the cuckoo module it completes fine.  Every time I try to run it standalone, then it crashes on me.

**The standalone command I use.**
_(Yes, I disable processing in cuckoo.conf before running this.)_

```
./process.py -d -r -p 4 auto
```

Here's the debug output from a recent run (both methods) on a sample that worked in my version installed from June.
- Standalone Run (fails): http://pastebin.com/GLT4pZXd
- Non-Standalone Run (succeeds):  http://pastebin.com/nYH5PkYE

**The error reported is:**

```
DEBUG:lib.cuckoo.core.plugins:Running signature "webmail_phish"
ERROR:root:Exception when processing task ID 5.
Traceback (most recent call last):
  File "./process.py", line 110, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
NameError: global name 'task_id' is not defined
```

Any suggestions on what I'm doing wrong, is something in process.py acting up, or is it my python setup?  Although it does work fine with all the other python tools I use at the moment.

Thanks for your time.

**Comment by brad-sp** [comment]
Should be fixed now, thanks!

**Comment by fulco** [comment]
I just reran with a brand new wiped install.  I now get the following when attempting to run in auto.  I should note when I switched off mongo in reporting.conf and switched to elasticsearch, the problem went away. 

Everything else looks identical to my previous message.

```
DEBUG:lib.cuckoo.core.plugins:Running signature "webmail_phish"
ERROR:root:Exception when processing task ID 10.
Traceback (most recent call last):
  File "./process.py", line 142, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
NameError: global name 'mongoconf' is not defined

```

Thanks for the time and work.

**Comment by KillerInstinct** [comment]
This will fix it. I never changed the config variable for the mongodb stuff when I integrated ES.

https://github.com/brad-accuvant/cuckoo-modified/pull/145

Multiprocessing traceback masked the actual issue -- thanks for spotting this.

**Comment by fulco** [comment]
Much appreciated!
