### ISSUE TITLE
Auto Processing is broken

### ISSUE THREAD

**Issue by blaquee** [brad-accuvant/cuckoo-modified#143]
I'm not sure at which point this happened but auto procesing using the process.py script now spits out an error.

```
Traceback (most recent call last):
  File "process.py", line 110, in autoprocess
    ar.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
NameError: global name 'task_id' is not defined
```

The change may be due to the removal of the task_id argument in the process function:

```
def process(task_id, target=None, copy_path=None, report=False, auto=False):
```

The newest commits omit this and uses instead the Task argument

```
def process(target=None, copy_path=None, task=None, report=False, auto=False):
```

And inside the main it looks like task is being converted to a dict().
    process(task=task.to_dict(), report=args.report)

Where prior it was asserted to int.
    process(int(args.id), report=args.report)

**Comment by blaquee** [comment]
I should add that this error only occurs if using process.py with auto argument. if you explicitly pass a task id, it will work fine. But I typically use process as a performance feature and leave it at auto

**Comment by brad-sp** [comment]
This should have been fixed last night already, please update to the latest release.
