### ISSUE TITLE
error on web when using ElasticSearch

### ISSUE THREAD

**Issue by lordremorin** [brad-accuvant/cuckoo-modified#151]
need to update /web/compare/views.py to support ES

**Comment by KillerInstinct** [comment]
Will get to this sometime this upcoming week. Also need to update api/views.py :)

Thanks.

**Comment by KillerInstinct** [comment]
This should do it:
https://github.com/brad-accuvant/cuckoo-modified/pull/160

Let me know if you run into any issues.
