### ISSUE TITLE
ERROR: Analysis failed: The package "modules.packages.doc" start function raised an error: Unable to find any Microsoft Office Word executable.

### ISSUE THREAD

**Issue by rprasko** [brad-accuvant/cuckoo-modified#158]
I received this error trying to submit a .doc file into the Cuckoo Platform. I was wondering if that is something that is found on the VM side or if there is an error trying to submit the file into the actual VM. Any help would be greatly appreciated.

**Comment by brad-sp** [comment]
Is Word installed in the guest VM?  If so, at what path?  Is it 32 or 64-bit?
