### ISSUE TITLE
[lib.cuckoo.core.plugins] WARNING: The reporting module "MAEC41Report" has missing dependencies: Unable to import cybox (install with `pip install cybox`)

### ISSUE THREAD

**Issue by rprasko** [brad-accuvant/cuckoo-modified#159]
I receive this error anytime that Cuckoo is trying to create a report on the web server. I have downloaded MAEC and Cybox seperately using the following

pip install cybox==2.0.1.4 
pip install maec==4.0.1.0

Not sure where this issue is occuring

**Comment by brad-sp** [comment]
What's the output of python -c "import cybox" ?

**Comment by rprasko** [comment]
Using: python -c "import cybox" on terminal
    Nothing shows up

I tried other various ways and I receive syntax errors

**Comment by brad-sp** [comment]
Create a file with the following contents:

import cybox
import cybox.utils.nsparser
from cybox.utils import Namespace
from cybox.core import Object
from cybox.common import ToolInformation
from cybox.common import StructuredText

And then run python on it and give me the output.

**Comment by brad-sp** [comment]
BTW, try installing newer versions of both:
pip install cybox==2.1.0.9
pip install maec==4.1.0.11

These are the versions mentioned in the documentation

**Comment by rprasko** [comment]
Both issues have been resolved with the Microsoft word and MAEC/Cybox...
Thank you
