### ISSUE TITLE
[lib.cuckoo.core.scheduler] ERROR: Cannot acquire machine: No machines match selection criteria

### ISSUE THREAD

**Issue by JonathanPhillips** [brad-accuvant/cuckoo-modified#164]
Got this error on two seperate machines when trying to submit a file for analysis. I've got regular cuckoo on both working normally but want to try this modified version. I'm obviously overlooking something. Double checked the conf files and the vm labels, names, etc. Any ideas?

**Comment by KillerInstinct** [comment]
Can you provide the error logs?

**Comment by brad-sp** [comment]
This can happen if you submitted a machine tag for the analysis that doesn't exist for any of the listed machines.  It can also happen if you submit a 64-bit PE but don't have any 64-bit VMs (or at least no VM with the "64_bit" tag).

**Comment by JonathanPhillips** [comment]
That's exactly what it was. I was trying to submit a 64 bit PE but didn't have the vm tagged as such.  Thanks

**Comment by SmartResearcherME** [comment]
Hi @brad-accuvant  @JonathanPhillips  I am experiencing the same issue with cuckoo modified while submitting x64 bit executable to windows 7 x64. I also tried renaming tag to "win7_64_bit" but for me issue is still there.  submission of 32 bit binaries is working fine.

 Any suggestion ?

**Comment by learner012** [comment]
I tried adding the tags via below command:
"python machine.py --tags Win7_64_bit Win7"
where "Win7_64_bit" is the tag name and "Win7" is the VMname.

Is that correct? If yes, I still could not analyse 64 bit file even though I have a 64 bit VM.

Thanks in advance

**Comment by learner012** [comment]
@brad-accuvant - Can you please help me here?
I have even rename the VM to "Win7_64_bit", still no luck with 64 bit files.
Although 32 bit files are running perfectly fine.
