### ISSUE TITLE
Creating postgres database fails

### ISSUE THREAD

**Issue by seanthegeek** [brad-accuvant/cuckoo-modified#174]
CuckooDatabaseError: Unable to create or connect to database: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index" DETAIL: Key (typname, typnamespace)=(samples_id_seq, 2200) already exists. [SQL: '\nCREATE TABLE samples (\n\tid SERIAL NOT NULL, \n\tfile_size INTEGER NOT NULL, \n\tfile_type TEXT NOT NULL, \n\tmd5 VARCHAR(32) NOT NULL, \n\tcrc32 VARCHAR(8) NOT NULL, \n\tsha1 VARCHAR(40) NOT NULL, \n\tsha256 VARCHAR(64) NOT NULL, \n\tsha512 VARCHAR(128) NOT NULL, \n\tssdeep VARCHAR(255), \n\tPRIMARY KEY (id)\n)\n\n']

**Comment by seanthegeek** [comment]
For whatever reason, I did not encounter this bug on a new system. Closing this issue.

**Comment by sayonsom** [comment]
Unfortunately, I am still encountering this bug. Might be worth revisiting this bug!
