### ISSUE TITLE
ElasticsearchDB Fails when performing object mapping for result["signatures"]

### ISSUE THREAD

**Issue by MerX1030** [brad-accuvant/cuckoo-modified#176]
Got an error when processing the report for this sample:
MD5 a6061196c9df9364d48c01bea83d6cb7
SHA1 18e7d740bf76ef0c700bf0b78feb9a0556d9f5bc

The error is as follows:
RequestError: TransportError(400, u'MapperParsingException[object mapping for [analysis] with array for [signatures] tried to parse as array, but got EOF, is there a mismatch in types for the same field?]')

I only used the community signatures.

**Comment by KillerInstinct** [comment]
I am unable to replicate this (http://i.imgur.com/rYQPnam.png)

Do you have any logs from processing? Otherwise can you pastebin/gist me the signatures dict?

**Comment by MerX1030** [comment]
Sorry. I was on PTO. Here you go:
http://pastebin.com/YrqTwzyn

**Comment by KillerInstinct** [comment]
Is your elastic config default? Otherwise, I'm really not sure in this case, the list of dicts looks fine. Dumb luck, but have you tried re-reporting?

**Comment by MerX1030** [comment]
Yeah, it's on default. I tried re-reporting but still got the same error.
I'll try to remove entries from the signatures dict one by one and see what's causing the problem.

**Comment by MerX1030** [comment]
Did a couple of tests and found out that the error is somehow caused by signatures["data"] entry.
Though I don't really know why it caused an error.

**Comment by KillerInstinct** [comment]
Do you happen to know which signature?

**Comment by MerX1030** [comment]
The signature in question is packer_entropy.

**Comment by KillerInstinct** [comment]
That is odd .. are you able to test a few things?

1) Replace the ":" with "-"
2) Replace the "|" with "-"

I'd be curious if that's interfering. What version of ElasticSearch are you running?

**Comment by MerX1030** [comment]
I'm using version 1.4.5.
I'll try doing what you're suggesting later and let you know of the results.
Thanks!

**Comment by MerX1030** [comment]
Upgraded ElasticSearch to version 1.7 and it worked just fine!
Closing this issue.

**Comment by KillerInstinct** [comment]
I am also using 1.4.5 -- don't think the version is an issue. Curious if there was some internal issue with ES in your case.
