### ISSUE TITLE
sort_pcap breaks 'hosts' summary association of ip to hostname

### ISSUE THREAD

**Issue by begosch** [brad-accuvant/cuckoo-modified#19]
So, when using sorted_pcap, the processing of the pcap is run in a non-deterministic order.  When I implemented the function to associate hostnames with ip address in our unique hosts view, it was under the assumption that the UDP traffic (dns resolution) would be processed in order with the TCP traffic; now with sorted_pcap, the udp is not processed until after the TCP traffic.  There are a couple of ways to fix the implementation, but none are really elegant.  I would like to get your thoughts on this....

**Comment by brad-sp** [comment]
Yes, I noticed the same.  That area of the code isn't really in an area of my expertise, so your guess would be as good (or better) than mine there.

**Comment by brad-sp** [comment]
Fixed by your recent commit, thanks ;)
