### ISSUE TITLE
Issue with Malheur

### ISSUE THREAD

**Issue by lehuff** [brad-accuvant/cuckoo-modified#213]
Activating Malheur after installing and submitting a job gives the following error:

malheur: unrecognized option '--input.format'
Usage: malheur [options] <action> <dataset>

Actions:
  distance       Compute distance matrix for malware reports
  prototype      Extract prototypes from malware reports
  protodist      Compute distance matrix for prototypes
  cluster        Cluster malware reports into similar groups
  classify       Classify malware reports using labeled prototypes
  increment      Incremental analysis of malware reports
  info           Print information about internal state of Malheur

Options:
  -s,  --state_dir <dir>       Set directory for internal state.
  -o,  --output_file <file>    Set output file for analysis results.
  -c,  --config_file <file>    Set configuration file.
  -n,  --dry                   Dry run. Don't change internal state.
       --reset                 Reset internal state of Malheur.
       --fvec_dump <file>      Dump feature vectores in LibSVM format.
  -C,  --print_config          Print the current configuration.
  -D,  --print_defaults        Print the default configuration.
  -v,  --verbose               Increase verbosity.
  -V,  --version               Print version and copyright.
  -h,  --help                  Print this help screen.

See manual page malheur(1) for more information.
2015-09-24 09:25:02,574 [lib.cuckoo.core.plugins] WARNING: The reporting module "Malheur" returned the following error: Failed to perform Malheur classification: [Errno 2] No such file or directory

**Comment by brad-sp** [comment]
Update to the latest version, your malheur.py is outdated.

**Comment by lehuff** [comment]
Updated, now I don't get any errors, but I don't see any malheur reports after running analysis. Verified enabled in confs.

**Comment by brad-sp** [comment]
Are you looking in storage/malheur/reports ?

**Comment by lehuff** [comment]
Please smack me and close this ;)

**Comment by brad-sp** [comment]
No worries.
