### ISSUE TITLE
Segmentation Fault upon completing analysis

### ISSUE THREAD

**Issue by BrandonEckert** [brad-accuvant/cuckoo-modified#223]
Good afternoon, I just did a git-pull to receive the newest cuckoo-modified files, and tried doing a submission. Everything works as expected, except when ./cuckoo.py states that "Analysis completed Successfully", I immediately receive a "Segmentation fault" and no reports are generated.  Any ideas? I have tried submitting files I had previously submitted successfully in the past, and the issue still occurs.

**Comment by KillerInstinct** [comment]
Is it a PDF? Is malheur enabled?

**Comment by BrandonEckert** [comment]
They are word documents.

**Comment by brad-sp** [comment]
Need more information to do anything with this report.  A VT hash for one of the files causing the crash would be a good start.
