### ISSUE TITLE
/api/ fail without this

### ISSUE THREAD

**Issue by doomedraven** [brad-accuvant/cuckoo-modified#23]
Hi, you need import this changes to get work /api/ in your cuckoo https://github.com/KillerInstinct/cuckoo-modified/commit/b75c2de392cfe7861226dcc709670ec52b603504
because at the moment is gives 500, as get_config not exists

**Comment by brad-sp** [comment]
Thanks, was a known issue and was just waiting for the fix at the time :) Cherry-picked it now.
