### ISSUE TITLE
Truncation of target column in tasks table upon db_migration

### ISSUE THREAD

**Issue by wmetcalf** [brad-accuvant/cuckoo-modified#24]
https://github.com/brad-accuvant/cuckoo-modified/blob/master/utils/db_migration/versions/from_1_2_to_1_2-accuvant-add_statistics.py

You are setting the target column that was previously set to unlimited Text() to String(255). This is causing truncation of URL/file tasks to 255 chars using db's with migrated data.

**Comment by brad-sp** [comment]
When was it unlimited?  If it's a bug, upstream is affected too, as all database upgrade scripts present are truncating to 255 characters (from_0_6_to_1_1, from_1_1_to_1_2).

**Comment by wmetcalf** [comment]
I'ts unlimited now in upstream. It's also unlimited in your fork now if creating a new db. It is only not unlimited if you use this migration script, which migrates the data and truncates the column.

https://github.com/brad-accuvant/cuckoo-modified/blob/master/lib/cuckoo/core/database.py#L276

**Comment by wmetcalf** [comment]
I think all you need to do is set the migration script to use the same construct what is reflected in  /lib/cuckoo/core/database.py at least in my testing alembic didn't seem to mind this change.

i.e.
            sa.Column("target", sa.Text(), nullable=False),

**Comment by brad-sp** [comment]
Yes, though I'll need to modify all the old migration scripts and then also create a new one that will fix existing setups broken by the upgrade.

**Comment by brad-sp** [comment]
Nevermind, it seems that it should be enough to just fix the old migration scripts, as all new tasks will be created with Text().  It should be fixed now, thanks!
