### ISSUE TITLE
Super sleepy loop :) time.sleep() in python is sec's not msec browser aux module..

### ISSUE THREAD

**Issue by wmetcalf** [brad-accuvant/cuckoo-modified#26]
https://github.com/brad-accuvant/cuckoo-modified/blob/master/analyzer/windows/modules/auxiliary/browser.py#L34

time.sleep() in python is in secs not msec's you are sleeping 1000 seconds for each iteration of the loop :). Should be time.sleep(1)

https://docs.python.org/2/library/time.html

**Comment by brad-sp** [comment]
Thanks, fixed!
