### ISSUE TITLE
Sandbox aware malware

### ISSUE THREAD

**Issue by Fryyyyy** [brad-accuvant/cuckoo-modified#267]
The latest version of Upatre seems to completely avoid running in the Cuckoo environment

7de446264a82a297196f8f3e1a53ee7a08fc6423b458cc20bd285a01b361dbfe

**Comment by jbremer** [comment]
Seems to run `NtQueryInformationSystem(SystemProcessorPerformanceInformation)` right before quiting the analysis so I'm going to assume that's a new detection technique :-)

**Comment by Fryyyyy** [comment]
You're the best

**Comment by Fryyyyy** [comment]
I don't see any change after these new DLLs....from my cursory examination you're looking for the call to succeed before modifying the performance information, but in my sandbox the call fails:

2015-11-03 16:35:12,484     748     0x004032a6 0x00403017   NtQuerySystemInformation    SystemInformationClass: SystemProcessorPerformanceInformation   failed  INFO_LENGTH_MISMATCH
2015-11-03 16:35:12,484     748     0x004032fa 0x00403017   NtQuerySystemInformation    SystemInformationClass: SystemInterruptInformation  success     0x00000000

**Comment by brad-sp** [comment]
Should be fixed now, there was an additional case I didn't handle -- if the first call fails and returns 0 for the return length, then it checks against the idle time for SystemPerformanceInformation (our enum and the pretty-printing had the wrong values, so it incorrectly labeled it as SystemInterruptInformation).

-Brad
