### ISSUE TITLE
ERROR: Cannot connect to libvirt

### ISSUE THREAD

**Issue by lunachy** [brad-accuvant/cuckoo-modified#269]
I set libvirtd.conf.
max_clients = 1024
min_workers = 50
max_workers = 512
max_requests = 1000
max_client_requests = 1000
There' too many open files. I think it results in "Cannot connect to libvirt". Any idea?
![libv](https://cloud.githubusercontent.com/assets/10249962/11392029/e5b35d70-9391-11e5-9206-af019aefeffd.png)
![too man](https://cloud.githubusercontent.com/assets/10249962/11392036/ecbfffe2-9391-11e5-8c09-c1555b51522d.png)
![too](https://cloud.githubusercontent.com/assets/10249962/11392040/f3894d60-9391-11e5-8de7-c91392971913.png)

**Comment by brad-sp** [comment]
This is even with the 65535 fd limit?

**Comment by lunachy** [comment]
Yes, I already set ulimit -n 65535. Today I set ulimit -n 1000000 and test it, I will check the results tomorrow.

**Comment by brad-sp** [comment]
You're trying to push beyond the capabilities of the Cuckoo architecture, so I don't see this particular use-case working out without significant development effort on your end.

-Brad
