### ISSUE TITLE
Analysis failed: [Errno 22] invalid mode ('w') or filename: 'C:\\564.ini'

### ISSUE THREAD

**Issue by timleedy** [brad-accuvant/cuckoo-modified#27]
This is likely user error on my part, but I'm getting the following error when running samples:
Analysis failed: The package "modules.packages.exe" start function encountered an unhandled exception: [Errno 22] invalid mode ('w') or filename: 'C:\564.ini'

The VM is windows 7 32 with UAC turned off.  I don't get the error when using the code from the main cuckoo branch.

**Comment by brad-sp** [comment]
It's a problem with the VM configuration.  Another user had reported it previously, and the fix that worked for him was: http://answers.microsoft.com/en-us/windows/forum/windows_7-security/windows-7-cannot-save-files-to-c-even-after-making/938f2b50-b063-475b-8c5e-905d136df2e3?tab=AllReplies#tabs

**Comment by sdsponger** [comment]
Yup, problem was on my VM side.  I was using another account with admin creds, not the local Administrator account.  I switched to that account and all is good.

Thanks

**Comment by SmartResearcherME** [comment]
@brad-accuvant  @sdsponger @timleedy  

I believe this is Python IO error and not permission error.
When i submit sample for analysis i got this error.

 ERROR: Analysis failed: The package "modules.packages.exe" start function encountered an unhandled exception: [Errno 22] invalid mode ('w') or filename: 'C:\\3596.ini'

Something is wrong with python code of cuckoo.

Earlier i had permission denied issue which was solved with the help of http://www.thewindowsclub.com/you-dont-have-permission-to-save-in-this-location

Please help..

**Comment by SmartResearcherME** [comment]
There are 4 slashes before the name of .ini file ... Is it the issue of calling function ???

package \"modules.packages.exe\" start function encountered an unhandled exception: [Errno 22] invalid mode ('w') or filename: 'C:\\4084.ini

**Comment by SmartResearcherME** [comment]
I manually killed the pythonw.exe and restarted the os and then start it again.
