### ISSUE TITLE
Mistake in latest commit regarding executed commands

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#28]
In behavior.py you added "executed_commands" but within the API calls check you are referring to and saving in "executed_processes".
This should be changed to "executed_commands".

Please correct this mistake.

Thanks

**Comment by brad-sp** [comment]
This was already fixed 6 or so hours before your post ;) https://github.com/brad-accuvant/cuckoo-modified/commit/2515da7cb230de43db6e868bf7ba4a764cf259c1
