### ISSUE TITLE
Analysis crashed cuckoomon

### ISSUE THREAD

**Issue by v3r5ace** [brad-accuvant/cuckoo-modified#282]
Got a signature popping on a piece of malware with the message "Crashed cuckoomon during analysis. Report this issue to the github repo"

pid: 2388
message: Exception reported at offset 0xf241 in cuckoomon itself

**Comment by KillerInstinct** [comment]
@lpaine Late response, as I don't really monitor this repo anymore.

Please report this to the maintained repo: https://github.com/spender-sandbox/cuckoo-modified/issues

Also some more logs would be great. If you could give us the log output when clicking "Show Log" in a gist/pastebin for the "debug" log thats in the overview page (top right of the Analysis Row)

**Comment by v3r5ace** [comment]
Hey, this issue was resolved on the main branch....I raised an issue there. I should have closed out this one, sorry! 

## 

Luke Paine
Quality Assurance Specialist
Infocyte, Inc
(405)-431-7888
www.infocyte.com
