### ISSUE TITLE
Huge memory leaks after running for a few days

### ISSUE THREAD

**Issue by danielgindi** [brad-accuvant/cuckoo-modified#283]
Sending tasks here and there, running for a few days, we got to a point where the `python` process weights more than 8GB in RAM.

Any known source for this issue?

**Comment by KillerInstinct** [comment]
Firstly, I'll state that I'm not having this issue.

Secondly, this repo is no longer maintained, please post issue tracking to:
https://github.com/spender-sandbox/cuckoo-modified/issues

Third, as I'm not experiencing this with ubuntu 14.04, we'll need some information on your rig. OS, Python Versions, configs (are you using ram_boost?) etc. But please post to the above mentioned issue tracker.
