### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by fulco** [brad-accuvant/cuckoo-modified#30]
I have been running this for a few months.  I went to upgrade today and have kept getting this error.  I tried a fresh pull and wiped the MySQL DB.  I downloaded the zip.  Extracted it.  Changed a few config items to match my install.  The analysis runs fine.  However, when I try to go to the report (http://127.0.0.1:8000/analysis/1/) it fails with this message: 

NoReverseMatch at /analysis/1/

Reverse for 'analysis.views.filereport' with arguments '(1, u'json')' and keyword arguments '{}' not found. 0 pattern(s) tried: []

http://dpaste.com/39ZBHJ0

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/analysis/1/

Django Version: 1.6.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare',
 'api',
 'ratelimit')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders',
 'ratelimit.middleware.RatelimitMiddleware')

Template error:
In template /home/darian/Downloads/cuckoo-modified-master/web/templates/analysis/reports/index.html, error at line 2
   Reverse for 'analysis.views.filereport' with arguments '(1, u'json')' and keyword arguments '{}' not found. 0 pattern(s) tried: []

```
 1 : <div class="alert alert-info center">


   2 :     <a class="btn btn-primary btn-small" href=" {% url "analysis.views.filereport" analysis.info.id "json" %} ">Download JSON Report</a><br />


   3 :     <a class="btn btn-primary btn-small" href="{% url "analysis.views.filereport" analysis.info.id "html" %}">Download HTML Report</a><br />


   4 :     <a class="btn btn-primary btn-small" href="{% url "analysis.views.filereport" analysis.info.id "pdf" %}">Download PDF Report</a><br />


   5 :     <a class="btn btn-primary btn-small" href="{% url "analysis.views.filereport" analysis.info.id "maec" %}">Download MAEC Report</a><br />


   6 :     <a class="btn btn-primary btn-small" href="{% url "analysis.views.filereport" analysis.info.id "metadata" %}">Download Metadata Report</a><br />


   7 : </div>

```

   8 : 

Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/usr/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
2.             return func(request, _args, *_kwargs)
   File "/home/darian/Downloads/cuckoo-modified-master/web/analysis/views.py" in report
3.                               context_instance=RequestContext(request))
   File "/usr/lib/python2.7/dist-packages/django/shortcuts/**init**.py" in render_to_response
4.     return HttpResponse(loader.render_to_string(_args, *_kwargs), **httpresponse_kwargs)
   File "/usr/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
5.         return t.render(context_instance)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
6.             return self._render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py" in _render
7.         return self.nodelist.render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
8.                 bit = self.render_node(node, context)
   File "/usr/lib/python2.7/dist-packages/django/template/debug.py" in render_node
9.             return node.render(context)
   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
10.         return compiled_parent._render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in _render
11.         return self.nodelist.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
12.                 bit = self.render_node(node, context)
    File "/usr/lib/python2.7/dist-packages/django/template/debug.py" in render_node
13.             return node.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
14.         output = self.nodelist.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
15.                 bit = self.render_node(node, context)
    File "/usr/lib/python2.7/dist-packages/django/template/debug.py" in render_node
16.             return node.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
17.             result = block.nodelist.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
18.                 bit = self.render_node(node, context)
    File "/usr/lib/python2.7/dist-packages/django/template/debug.py" in render_node
19.             return node.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
20.         return self.render_template(self.template, context)
    File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py" in render_template
21.         output = template.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
22.             return self._render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in _render
23.         return self.nodelist.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/base.py" in render
24.                 bit = self.render_node(node, context)
    File "/usr/lib/python2.7/dist-packages/django/template/debug.py" in render_node
25.             return node.render(context)
    File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
26.                         six.reraise(*exc_info)
    File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
27.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
    File "/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py" in reverse
28.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, _args, *_kwargs))
    File "/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py" in _reverse_with_prefix
29.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /analysis/1/
Exception Value: Reverse for 'analysis.views.filereport' with arguments '(1, u'json')' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**My Settings:**
Settings
Using settings module web.settings
Setting     Value
VTDL_PATH   

'/tmp/'

LOCAL_SETTINGS  

True

USE_L10N    

True

VTDL_INTEL_KEY  

u'********************'

USE_THOUSAND_SEPARATOR  

False

CUCKOO_PATH     

'/home/darian/Downloads/cuckoo-modified-master/web/..'

CSRF_COOKIE_SECURE  

False

LANGUAGE_CODE   

'en-us'

ROOT_URLCONF    

'web.urls'

MANAGERS    

()

TEMPLATE_LOADERS    

('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')

DEFAULT_CHARSET     

'utf-8'

SESSION_SERIALIZER  

'django.contrib.sessions.serializers.JSONSerializer'

STATIC_ROOT     

''

GATEWAYS    

{}

ALLOWED_HOSTS   

['*']

MESSAGE_STORAGE     

'django.contrib.messages.storage.fallback.FallbackStorage'

EMAIL_SUBJECT_PREFIX    

'[Django] '

SEND_BROKEN_LINK_EMAILS     

False

STATICFILES_FINDERS     

('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')

SESSION_CACHE_ALIAS     

'default'

SESSION_COOKIE_DOMAIN   

None

SESSION_COOKIE_NAME     

'sessionid'

ADMIN_FOR   

()

TIME_INPUT_FORMATS  

('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')

DATABASES   

{}

FILE_UPLOAD_PERMISSIONS     

None

MONGO_DB    

'cuckoo'

FILE_UPLOAD_HANDLERS    

('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')

DEFAULT_CONTENT_TYPE    

'text/html'

MOLOCH_NODE     

'cuckoo3'

APPEND_SLASH    

True

FIRST_DAY_OF_WEEK   

0

DATABASE_ROUTERS    

[]

YEAR_MONTH_FORMAT   

'F Y'

STATICFILES_STORAGE     

'django.contrib.staticfiles.storage.StaticFilesStorage'

CACHES  

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

SERVER_EMAIL    

'root@localhost'

MOLOCH_ENABLED  

False

MIDDLEWARE_CLASSES  

('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders',
 'ratelimit.middleware.RatelimitMiddleware')

USE_I18N    

True

THOUSAND_SEPARATOR  

','

SECRET_KEY  

u'********************'

LANGUAGE_COOKIE_NAME    

'django_language'

DEFAULT_INDEX_TABLESPACE    

''

MOLOCH_BASE     

'https://172.18.100.105:8005/'

TRANSACTIONS_MANAGED    

False

LOGGING_CONFIG  

'django.utils.log.dictConfig'

RATELIMIT_VIEW  

'api.views.limit_exceeded'

WSGI_APPLICATION    

'web.wsgi.application'

TEMPLATE_DEBUG  

True

X_FRAME_OPTIONS     

'SAMEORIGIN'

AUTHENTICATION_BACKENDS     

('django.contrib.auth.backends.ModelBackend',)

FORCE_SCRIPT_NAME   

None

USE_X_FORWARDED_HOST    

False

SIGNING_BACKEND     

'django.core.signing.TimestampSigner'

SESSION_COOKIE_SECURE   

False

CSRF_COOKIE_DOMAIN  

None

FILE_CHARSET    

'utf-8'

DEBUG   

True

SESSION_FILE_PATH   

None

DEFAULT_FILE_STORAGE    

'django.core.files.storage.FileSystemStorage'

INSTALLED_APPS  

('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare',
 'api',
 'ratelimit')

VTDL_ENABLED    

False

LANGUAGES   

(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy-nl', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-tw', 'Traditional Chinese'))

COMMENTS_ALLOW_PROFANITIES  

False

STATICFILES_DIRS    

('/home/darian/Downloads/cuckoo-modified-master/web/static',)

PREPEND_WWW     

False

SECURE_PROXY_SSL_HEADER     

None

SESSION_COOKIE_HTTPONLY     

True

DEBUG_PROPAGATE_EXCEPTIONS  

False

MONTH_DAY_FORMAT    

'F j'

LOGIN_URL   

'/accounts/login/'

SESSION_EXPIRE_AT_BROWSER_CLOSE     

False

TIME_FORMAT     

'P'

AUTH_USER_MODEL     

'auth.User'

DATE_INPUT_FORMATS  

('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')

CSRF_COOKIE_NAME    

'csrftoken'

EMAIL_HOST_PASSWORD     

u'********************'

PASSWORD_RESET_TIMEOUT_DAYS     

u'********************'

CACHE_MIDDLEWARE_ALIAS  

'default'

SESSION_SAVE_EVERY_REQUEST  

False

NUMBER_GROUPING     

0

SESSION_ENGINE  

'django.contrib.sessions.backends.db'

CSRF_FAILURE_VIEW   

'django.views.csrf.csrf_failure'

CSRF_COOKIE_PATH    

'/'

LOGIN_REDIRECT_URL  

'/'

SESSION_COOKIE_PATH     

'/'

MONGO_PORT  

27017

DECIMAL_SEPARATOR   

'.'

IGNORABLE_404_URLS  

()

VTDL_PRIV_KEY   

u'********************'

LOCALE_PATHS    

()

TEMPLATE_STRING_IF_INVALID  

''

LOGOUT_URL  

'/accounts/logout/'

EMAIL_USE_TLS   

False

TEMPLATE_DIRS   

('templates',)

FIXTURE_DIRS    

()

EMAIL_HOST  

'localhost'

DATE_FORMAT     

'N j, Y'

MEDIA_ROOT  

''

DEFAULT_EXCEPTION_REPORTER_FILTER   

'django.views.debug.SafeExceptionReporterFilter'

ADMINS  

()

FORMAT_MODULE_PATH  

None

DEFAULT_FROM_EMAIL  

'webmaster@localhost'

MEDIA_URL   

''

DATETIME_FORMAT     

'N j, Y, P'

MAX_UPLOAD_SIZE     

26214400

SITE_ID     

1

DISALLOWED_USER_AGENTS  

()

ALLOWED_INCLUDE_ROOTS   

()

LOGGING     

{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}},
 'handlers': {'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True}},
 'version': 1}

SHORT_DATE_FORMAT   

'm/d/Y'

TEST_RUNNER     

'django.test.runner.DiscoverRunner'

CACHE_MIDDLEWARE_KEY_PREFIX     

u'********************'

TIME_ZONE   

None

FILE_UPLOAD_MAX_MEMORY_SIZE     

2621440

EMAIL_BACKEND   

'django.core.mail.backends.smtp.EmailBackend'

DEFAULT_TABLESPACE  

''

TEMPLATE_CONTEXT_PROCESSORS     

('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages')

SESSION_COOKIE_AGE  

1209600

SETTINGS_MODULE     

'web.settings'

USE_ETAGS   

False

LANGUAGES_BIDI  

('he', 'ar', 'fa', 'ur')

FILE_UPLOAD_TEMP_DIR    

None

INTERNAL_IPS    

()

STATIC_URL  

'/static/'

EMAIL_PORT  

25

USE_TZ  

False

SHORT_DATETIME_FORMAT   

'm/d/Y P'

PASSWORD_HASHERS    

u'********************'

ABSOLUTE_URL_OVERRIDES  

{}

CACHE_MIDDLEWARE_SECONDS    

600

CSRF_COOKIE_HTTPONLY    

False

DATETIME_INPUT_FORMATS  

('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')

MONGO_HOST  

'127.0.0.1'

EMAIL_HOST_USER     

''

PROFANITIES_LIST    

u'********************'

**Comment by brad-sp** [comment]
This should have been fixed already a few hours ago.  Sometimes changes are made across multiple commits, so I wouldn't recommend updating in the middle of the day while I'm still actively committing to the repo.
