### ISSUE TITLE
dist.py

### ISSUE THREAD

**Issue by mhanne0915** [brad-accuvant/cuckoo-modified#32]
Hi,
just found an error on dist.py after submitting a sample to dist.py:
[Error]
CRITICAL:cuckoo.distributed:Error submitting task (task #4, node mynode): 'task_id'

[my temporary solution]:
line 132: task.task_id = r.json()["task_id"] -> task.task_id = r.json()["task_ids"]

Not sure if this is the correct approach. But so far my setup runs smoothly. Help it helps;)

**Comment by brad-sp** [comment]
It's probably wrong, yes, but that file will disappear with the next git pull and be replaced by other upstream code, so I've applied your change for now.  Thanks!

**Comment by mhanne0915** [comment]
Thanks brad ;)
