### ISSUE TITLE
Ratelimit on webserver

### ISSUE THREAD

**Issue by hegusung** [brad-accuvant/cuckoo-modified#36]
Hi !

When I start the webserver : "python manage.py runserver 0.0.0.0:8080"

I get the following error when I load a page :
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    **import**(name)
  File "/media/raid5/Malware Analysis/cuckoo-modified/web/api/views.py", line 127, in <module>
    @ratelimit(key="ip", rate=raterps, block=rateblock)
TypeError: ratelimit() got an unexpected keyword argument 'key'

what's the problem ?

**Comment by brad-sp** [comment]
What version of django-ratelimit do you have?

**Comment by hegusung** [comment]
My version is 0.4.0

**Comment by KillerInstinct** [comment]
Try and upgrade if possible:

```
cuckoo@cuckoo:~$ pip list | grep django
django-ratelimit (0.5.0)
```
