### ISSUE TITLE
Problem using re2

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#39]
When starting the newest version of cuckoo I receive this error :
/modules/machinery/virtualbox.py", line 192, in _status
state = re.match(r"VMState=\"(\w+)\"", line, re.M|re.I)
AttributeError: 'module' object has no attribute 'M

This has something to do with re2 when installed on the machine, re2 doesn't support these attributes, only re does.

Can this be solved ?

Thanks.

**Comment by brad-sp** [comment]
Should be fixed now, I reverted to re on that particular file.

**Comment by dforce** [comment]
I think you have to do this for more files than the one I stated.
IGNORECASE, MULTILINE, I, M and DOTALL are no attributes for re2. All files where these are used will print an error.

**Comment by brad-sp** [comment]
I just reverted the change -- I think you may have installed the wrong version of re2.  If you use: https://github.com/axiak/pyre2 it will work fine.

> > > import re2
> > > print re2.IGNORECASE
> > > 2
> > > print re2.MULTILINE
> > > 8
> > > print re2.I
> > > 2
> > > print re2.M
> > > 8
> > > print re2.DOTALL
> > > 16

**Comment by dforce** [comment]
Yes, I installed the wrong version (https://github.com/facebook/pyre2/).

Now everything is working fine.

Thanks
