### ISSUE TITLE
Django API - /api/create/file Returning Error

### ISSUE THREAD

**Issue by steve-landy** [brad-accuvant/cuckoo-modified#44]
Is the API that is exposed via Django supposed to be completely functional or should the bottle.py API be utilized instead? I'm trying to integrate Cuckoo with CRITs (https://github.com/crits/crits) and the create file sends back the following error:

``` bash
curl -F file=@/home/cuckoo/Downloads/MALWARE/3c264ff1e097b4f35968a1c930087c2 -F machine="MALVIC1_winxpprosp3" http://10.30.98.150/api/tasks/create/file/
{
    "error_value": "No file was submitted", 
    "error": true
}
```

**Comment by KillerInstinct** [comment]
I am unable to replicate:

```
cuckoo@cuckoo:/cuckoo/personal-cuckoo$ curl -F file=@utils/dyre.exe -F machine="W7-x86-01" 127.0.0.1:8000/api/tasks/create/file/
{
    "url": [
        "None/submit/status/1516/"
    ],
    "data": "Task ID 1516 has been submitted",
    "error": false
}cuckoo@cuckoo:/cuckoo/personal-cuckoo$
```

(There's a typo bug in the json response, fixing that now -- but doesn't have anything to do with that error.)

Could you provide more info? Are you sure the file exists at that path? Do you have permission to read it?

**Comment by steve-landy** [comment]
I just tried again this morning. I made sure the cuckoo user owns the directory and the file trying to be submitted. I guess it was indeed a file permission issue.

Now I just need to figure out why the submission process isn't working with the **cuckoo_service** for **CRITs**

If you're interested here is the repo:
https://github.com/crits/crits_services/tree/master/cuckoo_service

Here is the complete output of my test this morning:

``` bash
cuckoo@cuckoo:~/Downloads/MALWARE$ ls -lh
total 2.6M
-rw-r--r-- 1 cuckoo cuckoo 906K Apr 29 17:48 0c72f2b13939911dff386019153c7678
-rwxr-xr-x 1 cuckoo cuckoo 537K Apr 29 17:58 0c72f2b13939911dff386019153c7678.zip
-rw-r--r-- 1 cuckoo cuckoo 690K Apr 29 17:45 63c264ff1e097b4f35968a1c930087c2
-rwxr-xr-x 1 cuckoo cuckoo 495K Apr 29 17:58 63c264ff1e097b4f35968a1c930087c2.zip
cuckoo@cuckoo:~/Downloads/MALWARE$curl -F file=@63c264ff1e097b4f35968a1c930087c2 -F machine="MALVIC1_winxpprosp3" http://10.30.98.150/api/tasks/create/file/
{
    "url": [
        "None/submit/status/45/"
    ],
    "data": "Task ID 45 has been submitted",
    "error": false
}cuckoo@cuckoo:~/Downloads/MALWARE$
```

**Comment by KillerInstinct** [comment]
Not sure honestly. But the API for Django should be pretty much backwards compatible for the File/URL task creation in api.py. Are you able to see what the JSON response it from submitting a file through CRITs? I can debug via those error message, but I don't use CRITs so I am unable to test with that specifically.

**Comment by steve-landy** [comment]
I'll take a look at it this evening and definitely get back to you with the request/response info being created by CRITs interacting with Cuckoo.

**Comment by steve-landy** [comment]
Here is the python requests post action from the CRITs cuckoo service:

``` python
        r = requests.post(self.base_url + '/api/tasks/create/file',
                          files=files, data=payload,
                          proxies=self.proxies)
```

Here are what the parameter values look like at the time of the post:

``` python
parameter 1 = http://10.30.98.150:80/api/tasks/create/file
parameter 2 (files) = {'file': (u'solo.exe', 'EXE_REDACTED_FOR_SPACE')}
parameter 3 (data) = {'machine': u'MALVIC1_winxpprosp3'}
parameter 4 (proxies) = {'http': '', 'https': ''}
```

Here is the response that I receive from the Cuckoo API:

``` python
{u'error_value': u'Method not allowed', u'error': True}
```

I also receive an error from the CRITs cuckoo_service that says:

``` python
Error running service: 'task_id'
```

I noticed in the cuckoo API that the file_create uses **task_ids** while the url_create uses **task_id** is there a particular reason for this?

**Comment by KillerInstinct** [comment]
A shot in the dark, but try adding a "/" to the end of the URI parameter (I believe django URL's cares about that)

```
self.base_url + '/api/tasks/create/file/',
```

As far as the task_id and task_ids discrepancy -- that's due to how I implemented URL submission. The Web UI doesn't allow for multiple URL submissions in one POST, so you can only submit one URL per API request due to that limitation (thus I didn't pluralize it). File submission however, supports submission of multiple files, and thus we should allow for multiple tasks to be submitted. I guess if we ever decide to allow for multiple URL's to be submitted, it would get changed to task_ids. I just chose not to when i originally wrote that code.

EDIT: I should note that upstream changed task_id to task_ids a while back. That was why I chose to implement it similarly. I noticed a similar issue in the CRITs issue tracker, FYI.

**Comment by steve-landy** [comment]
The "shot in the dark" actually worked :+1:. The missing slash (**/**) at the end of the URL did the trick as far as a successful submission.

The response is returning incorrectly though. The **http://example.tld/** keeps showing up with the response instead of the URL that I have set in the **conf/api.conf** file

Here is the response that I'm seeing come back:

``` python
{u'url': [u'http://example.tld/submit/status/49/'], u'data': u'Task ID 49 has been submitted', u'error': False}
```

This is what I have set in the **api.conf** file:

``` python
[api]
# IP-based rate limiting
ratelimit = yes
# IP/Domain to be used for help page + callback URL's
url = http://10.30.98.150
```

**Comment by KillerInstinct** [comment]
Make sure you manually restart your web service. Django (manage.py) doesn't restart on a config change as it's not part of the web settings.py. If you're using something like Apache, that will need restarted. However if you're using Nginx and a wsgi handler, the handler would need to be restarted/reloaded.

**Comment by steve-landy** [comment]
My fault, I kept restarting the Apache for CRITs and never restarted the Apache for Cuckoo (2 separate boxes).

I figured out why the CRITs cuckoo service is still bombing though even though the submission works fine. It can't find the task_id because it's not returned as part of the json response like the **utils/api.py**. 

``` python
 response["task_ids"] = task_ids
```

Would it make sense to place this as a return parameter in the response? If not, what would you recommend as the appropriate way for the cuckoo service to wait for a status if not able to get the associated **task_id** in the json response?

The cuckoo service uses the **/api/tasks/view/** API and uses a while loop to wait until a **status == 'reported'** is returned by the API.

**Comment by KillerInstinct** [comment]
Sure, I PR'ed this change -- feel free to implement it yourself:
https://github.com/brad-accuvant/cuckoo-modified/pull/46

**Comment by steve-landy** [comment]
@KillerInstinct, Everything is working as expected now with that change :+1: 

There's one piece of functionality not working though in regards to dropped files. The bottle API has a dropped files retrieval mechanism in the **tasks_report** API call (https://github.com/brad-accuvant/cuckoo-modified/blob/master/utils/api.py#L261) but that same functionality doesn't appear to be in the Django API.

Is there another API call that I may have overlooked using the Django API that can be used to retrieve dropped files?

Thanks for all the help thus far @KillerInstinct

**Comment by KillerInstinct** [comment]
I'll try and add functionality for this over the weekend. Probably via a seperate API node. I didn't like how api.py does it, because you should be able to view the reports in the native formats (for proper programatic ingestion). Zipping them up like that makes it a bit more tedious, and also breaks viewing them in a browser. Speaking of dropped files, will add in suricata files too.

**Comment by steve-landy** [comment]
This would be a great addition to the API. I'll be looking forward to testing it out and integrating it with CRITs.

**Comment by KillerInstinct** [comment]
This should do the trick: https://github.com/brad-accuvant/cuckoo-modified/pull/52
