### ISSUE TITLE
Analyzing  64bit dll

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#48]
Each time when I run the analysis of a 64bit dll I get following error message :
"Analysis failed : The package modules.packages.dll start function raised an error: Unable to find any rundll32.exe executable".

Any idea what is going wrong ?

Thanks

**Comment by brad-sp** [comment]
No idea, it correctly uses c:\windows\sysnative\rundll32.exe here with the latest version

**Comment by dforce** [comment]
Can I send you a sample so you can test it ?
I also ran it in a Win XP 64bit vm.

**Comment by brad-sp** [comment]
Sure, just give me a hash of something on VT

**Comment by dforce** [comment]
hash is 
159397bde334956dc5ed3703890eec13

VT
https://www.virustotal.com/en/file/86dd4792638883024ad4402dce75f358dd531b5d00c3994ba290e21fc9c638e4/analysis/

**Comment by brad-sp** [comment]
Works fine here, modulo there being any DllMain to run for it to analyze (would need to pass a specific option for that)

What's the guest OS?

**Comment by dforce** [comment]
Guest OS is Windows XP 64bit.

**Comment by brad-sp** [comment]
As in Windows 10?  We don't even support Windows 8 really yet, maybe try something that is supported ;)

**Comment by dforce** [comment]
No, Windows XP 64bit (modified in answer above)

**Comment by brad-sp** [comment]
Do you have 32-bit python installed in it?  Do both c:\windows\system32\rundll32.exe and c:\windows\syswow64\rundll32.exe exist in it?  does a os.path.exists("c:\windows\sysnative\rundll32.exe") return True in python in the guest?

**Comment by dforce** [comment]
Using python 32-bt.
Both files exists.
Running python script in guest returns False, can't find the pah to rundll32.exe.

How can I solve this ?

**Comment by brad-sp** [comment]
Install this Hotfix in the guest: https://support.microsoft.com/en-us/kb/942589  sysnative isn't available on XP 64-bit without it.

**Comment by dforce** [comment]
This didn't solved the problem, I receive False when I run your script in python.

**Comment by brad-sp** [comment]
Not sure then -- if you eventually find a solution, patches are welcome.  Keep in mind though that sysnative is required for other aspects of Cuckoo to work properly for 64-bit, including dropped files.

**Comment by dforce** [comment]
Running executables on Win XP 64bit doesn't give any trouble where everything works fine, even dropped files.
Only problem when running dlls.

**Comment by brad-sp** [comment]
It won't work fine.  Try running a 64-bit sample that drops files to c:\windows\system32, analyzer.py will be unable to obtain them because their path will be rewritten to c:\windows\sysnative, which your guest does not apparently support.

**Comment by dforce** [comment]
I installed the hotfix and I receive "True" hen os.path.exists to "c:\windows\sysnative".
When I do os.path.exists to "c:\windows\sysnative\rundll32.exe" I receive a False.

Is  there something I have to change more on my Windows XP 64-bit vm to get this working ?

**Comment by dforce** [comment]
Problem solved.
After reinstalling the hotfix all works now.

If using "os.path.exists("c:\windows\sysnative") and getting a positive result, is enough for everything getting working.
So to check in Windows you have to use the above python script.

Thanks for all the help.
