### ISSUE TITLE
Getting Bogus IRC Traffic from Network Processing

### ISSUE THREAD

**Issue by begosch** [brad-accuvant/cuckoo-modified#5]
Command : DIE

Parameter: 
y\xa1.\xf0\xaa\xee\x9e\x97Fy\x03\xf1kU\x1e\xea7\x8d\xa8\xa4\x03\xba\x88@h$\x115\xf2\x17\x8b3&\x1c&\xe7\x15[0\xf3\x97\x9c\xe3@\xbed!\xde\x1f \xc6x\xedp\xf3?\x1f#\x06\x87\x8b\xbb\xc1\xb4B6\x13\x82\x86\xea\xf0\xb8\x90\x81\x91\xb2\x96v]\xb5\x92-(\x1b\xbe\xaa\x94\xe9\x04\x19\x98\x0e@\xa5\x14"\xa0\xac>\x88\x81O\xcc\xf3`\x94 L!\xdb\x9c\xf9c\x11 \x0f\xd3\xdf\x99\xfe1\x90P\xe6\xb1\x86\x0b\x1f4\xdc\xf7)\xd5\x00\H\xca\x91?\xbcB[\xbd^m\xa7\xc4%\xc6e\x00?\xc36/\xb5%\x10\x92eq\xb5\x02\xfc\xac[\xa3\xab;B6}\xd4\x92\xc3\xca g\x1cB\x16\xba\xda\xdc\xc7\xe9M\x99\xb0\xbf+x\xa9\x10\xe6!\xeb\xb6\x8d\xdf\xfa\xbc\xf7?\xbe&+!Z\xebw\xd6\xe1\xe1\xa8\xec\xa6\x95m\xb0\xc7\x1b0K\x07\xdd{

Type: Client

**Comment by begosch** [comment]
Sample below showed bogus IRC traffic.

md5= 74d906df5fc5018f3cb08ce775d69595

**Comment by begosch** [comment]
sample provided does not resolve host in question... will need to find a more current sample

**Comment by KillerInstinct** [comment]
Updating this, the URL (defanged) causes bogus IRC traffic:
hxxp://izvestia.ru/

Will try and make the IRC parsing a bit more reliable. Seems theres no real 'parsing' and instead is just searching for keywords in TCP traffic and calling it IRC. Upstream bug.
