### ISSUE TITLE
Humanizing not working

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#51]
Just tested the latest version and noticed that there was no more humanizing in the vm.
No mouse point and nothing is clicked within the vm.

Is that normal ?

Thanks

**Comment by brad-sp** [comment]
Should be fixed now, was missing an import.  I've added exception reporting to catch stuff like this in the future.

**Comment by dforce** [comment]
Brad,

Thanks for the fix.
