### ISSUE TITLE
Problems with new added dlls

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#53]
After testing the latest version, with the new added dlls, there is no more process, behavior and network analysis. File gets started and immediatly ends the analysis in the vm.

I reverted back to the previous dlls and the problem was solved.

Maybe there is something wrong with the latest commited dlls.

Can this problem been solved ?

Thanks

**Comment by brad-sp** [comment]
Are you using the very latest version, or were you testing a version from this morning?  There was a bug for a few hours where NtWaitForSingleObject would crash cuckoomon if called with a NULL Timeout.  This was fixed some hours ago.

**Comment by dforce** [comment]
I tested the latest, commited 4 hours ago.

**Comment by brad-sp** [comment]
I can't reproduce the problem you're experiencing, so I'll need more information.

**Comment by dforce** [comment]
I just reinstalled the dlls and everything is working fine now.
Don't know what happened because I installed the latest version some 3 hours ago.
