### ISSUE TITLE
Automatic clicking for documents

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#54]
Lately I am analyzing a lot of documents with macros in it.

Is there a way to automaticaly click on these options during the analysis to enable the macros ?

Thanks

**Comment by KillerInstinct** [comment]
I have my VM's configured to allow macros to run globally. In the future I am going to add some registry key settings to the office packages to alleviate this. You could try adding "enable macros" to human.py, but I'm not sure if that button will be discovered, as human.py is rather simple. My best suggestion would be to go into your VM, change the setting and make a new snapshot.

**Comment by dforce** [comment]
Thanks for the info.
I will use your solution.
