### ISSUE TITLE
PyV8

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#57]
Where can I find PyV8 for Linux box ?

Each time I get for decoded data is :
PyV8 failed to parse the stream.

Is this normal ?

**Comment by KillerInstinct** [comment]
PyV8 parses ASCII/Javascript. You'll get that error if file magic is anything else.

You can get PyV8 by building it from source (how I installed it at least) via the below documentation:
https://code.google.com/p/pyv8/wiki/HowToBuild

I believe this was what I used:

```
apt-get install -y curl libboost-thread-dev libboost-all-dev libboost-dev libboost-python-dev git-core autoconf libtool subversion
export LIB=/usr
svn checkout -r19632 http://v8.googlecode.com/svn/trunk/ $LIB/v8
export V8_HOME=$LIB/v8
svn checkout http://pyv8.googlecode.com/svn/trunk/ $LIB/pyv8 && cd $LIB/pyv8 && python setup.py build && python setup.py install
```

**Comment by dforce** [comment]
Ok, thanks for the info.
It also gave the error message when it showed that the content was ASCII.
