### ISSUE TITLE
`delete_bin_off = on` Option Deletes Binary Prior to Analysis Processing with `process_results=off` Option

### ISSUE THREAD

**Issue by begosch** [brad-accuvant/cuckoo-modified#6]

**Comment by brad-sp** [comment]
Do you mean delete_bin_copy, or delete_original?  And is this with utils/process.py or via another method?

**Comment by begosch** [comment]
Sorry, I logged this bug with some rudimentary tests after a few beers.  Fixes to utils/process.py seemed to have fixed this issue. Closing.
