### ISSUE TITLE
Current version of cuckoomon dll's crash IE8-IE10

### ISSUE THREAD

**Issue by wmetcalf** [brad-accuvant/cuckoo-modified#60]
Current version of cuckoomon dll's seem to crash IE8-IE10 for URL tasks. Or I guess I should say IE doesn't ever fully load.  Process is started but doesn't do anything after this. "free=true" makes the problem go away.

Regards,

Will

**Comment by brad-sp** [comment]
Do you know what previous version didn't have this problem?

**Comment by wmetcalf** [comment]
The last version that I know worked was this one.

https://github.com/brad-accuvant/cuckoo-modified/commit/b32870979aba5ad051ad945761d99f38b93a8ddc

**Comment by brad-sp** [comment]
I've worked around it for now by removing the forced flush after each new API.  I'll eventually need to find a singular binary that can reproduce it -- I tried with injecting into just the main IE process, but that alone wasn't enough to reproduce.

**Comment by wmetcalf** [comment]
Seems to work. Awesome! Thanks!

**Comment by Alex7pol** [comment]
Hi Brad, can you share this dll with us, please?

**Comment by brad-sp** [comment]
The source is in the cuckoomon-modified repository, the binaries are in the cuckoo-modified repository in analyzer/windows/dll.
