### ISSUE TITLE
Tor and VirtualBox documentation

### ISSUE THREAD

**Issue by seanthegeek** [brad-accuvant/cuckoo-modified#63]
I'm trying to set up the ability to use a Tor transparent proxy on a per-sample basis with a VirtualBox VM. I've read the instructions in the FAQ, but I have very limited knowledge of IP tables, so I'm not sure what IP addresses to fill in where, assuming Tor is running on the same box as Cuckoo.

Right now, I am running inetsim on vboxnet0/192.168.56.1 so Cuckoo can sniff it, with the following iptables rule:

iptables -t nat -A PREROUTING -i vboxnet0 -j REDIRECT

I would like to maintain the ability to use inetsim by default when Tor is not enabled for the sample upload.

Can you provide more details on how to set this up?

**Comment by seanthegeek** [comment]
I created scripts to do this [here](https://github.com/seanthegeek/routetor)

**Comment by brad-sp** [comment]
Thanks again!
