### ISSUE TITLE
Too many screenshots during Office splashs

### ISSUE THREAD

**Issue by jmigot-tehtris** [brad-accuvant/cuckoo-modified#66]
Hi,

I wonder if it would be possible to add some nosplash markers to the doc, ppt and xls packages to prevent Office from displaying a very long moving splashscreen resulting in more than 50 screenshots of the same apparent screen.

If this seems ok to you, the modifiers are the following:
doc.py: return self.execute(word, "\"%s\" /q" % path, path)
ppt.py: return self.execute(powerpoint, "\"%s\" /s" % path, path)
xls.py: return self.execute(excel, "\"%s\" /e" % path, path)

I think there is no way to modify this directly in the guest VM because the programs are launched directly in python (at least I tried to add these markers in some registry keys without success).

**Comment by brad-sp** [comment]
Thanks, committed!
