### ISSUE TITLE
Substring Error in Analyzer.py

### ISSUE THREAD

**Issue by jhumble** [brad-accuvant/cuckoo-modified#7]
Log is below. I don't think this is tied to the sample, but I could be wrong. Just in case this one was on 0b5e895467d63e59815d10b97e214241. I'm seeing this happen occassionally (every 50-100 samples or so).

2015-03-04 10:36:09,280 [root] ERROR: Traceback (most recent call last):
  File "C:\dkadzmjt\analyzer.py", line 796, in <module>
    success = analyzer.run()
  File "C:\dkadzmjt\analyzer.py", line 551, in run
    self.prepare()
  File "C:\dkadzmjt\analyzer.py", line 515, in prepare
    servidx = s.index("services.exe")
ValueError: substring not found
Traceback (most recent call last):
  File "C:\dkadzmjt\analyzer.py", line 796, in <module>
    success = analyzer.run()
  File "C:\dkadzmjt\analyzer.py", line 551, in run
    self.prepare()
  File "C:\dkadzmjt\analyzer.py", line 515, in prepare
    servidx = s.index("services.exe")
ValueError: substring not found

**Comment by brad-sp** [comment]
What's the guest OS?

**Comment by jhumble** [comment]
Windows XP SP3

**Comment by brad-sp** [comment]
Could you have it log the value of 's'?  I don't know of any reason why that tasklist command should fail, especially when it's executing prior to any malware being run on the guest.

**Comment by jhumble** [comment]
s was an empty string.
I made the following patch, so I could see if stderr had any helpful info:
514         stdin, stdout, stderr = os.popen3("tasklist /V /FI \"IMAGENAME eq services.exe\"")
515         s = stdout.read()
516         rtncode = stdout.close()
517         stderr = stderr.read()

stderr returned the following: "INFO: No tasks running with the specified criteria."

Some googling turned up the following MS article:
http://support.microsoft.com/kb/2732840

Looks like tasklist just fails sometimes if load is too high. I'm probably running too many VMs. The only workaround I can think of is retry a couple times if this happens. If you'd like I can submit a pull request which catches this when it happens and retries x times before gracefully giving up.

**Comment by brad-sp** [comment]
Please do, thank you!

**Comment by jhumble** [comment]
Should be addressed by pull request 12.
I ran 1000 samples through with the change in place. tasklist failed on the first try on 3 of them, but succeeded on the second attempt in all of those cases.

And thank you! All of these changes you've been making are awesome. Feels like a whole new Cuckoo :)

**Comment by brad-sp** [comment]
Just merged it, thanks again!
