### ISSUE TITLE
Warning: Inconsistent arg count

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#76]
WARNING:lib.cuckoo.common.netlog:Inconsistent arg count (compared to arg names) on LdrGetDllHandle: {u'C': 1995373682, u'I': 11, u'args': [1, 0], u'P': 268455305, u'R': 268457032, u'T': 2960, u'r': 0, u't': 31} names [u'is_success', u'retval', u'FileName', u'ModuleHandle']

....
WARNING:lib.cuckoo.common.netlog:Inconsistent arg count (compared to arg names) on SetUnhandledExceptionFilter: {u'C': 1964928154, u'I': 13, u'args': [1, 0, Binary('uxtheme.dll', 0), 1942749184, Binary('DrawThemeBackground', 0), 0, 1942763906], u'P': 0, u'R': 0, u'T': 3796, u'r': 0, u't': 187} names [u'is_success', u'retval']

**Comment by brad-sp** [comment]
Is this with the latest version?  Seems like a log was corrupted. Is it reproducible at all?

**Comment by ghost** [comment]
Will re-open this issue once I've duplicated it using the latest version. Thank you.
