### ISSUE TITLE
Specifying port resultserver

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#86]
I am running my analysis on host-only connection for some virtual machines machines and bridge connections for other virtual machines.
I disabled the resultserver port in the cuckoo.conf and added the resultserver port in the virtualbox.conf.
I specified different ports for the 2 connections.
Now I receive this error message :
File "/data/virtualenvscuckoo/lib/cuckoo/core/resultserver.py", line 49, in **init**
    self.port = int(self.cfg.resultserver.port)
TypeError: int() argument must be a string or a number, not 'NoneType'

How can this problem be solved ?

Thanks

**Comment by brad-sp** [comment]
You need to leave the ip/port setting in cuckoo.conf enabled.  Whatever you choose in virtualbox.conf will override that ip/port setting for the specific named machine.

**Comment by dforce** [comment]
Thanks, problem solved.
