### ISSUE TITLE
some Office (xml-based) malware unable to analyze by cuckoo

### ISSUE THREAD

**Issue by mhanne0915** [brad-accuvant/cuckoo-modified#89]
Some of the Macro malware (xml-based.) are inaccurately analyzed by cuckoo. Cuckoo extracts the office file and it analyzes the extracted files instead of the office file itself.
Sample:
Trojan-Downloader.MSWord.Agent.mt:
https://www.virustotal.com/en/file/cc76cf4609e82a18c339a9095a11396ae312a51383f01bf808f830dbc9c8b771/analysis/

Contents:
[Content_Types].xml
_rels/.rels
theme/theme/themeManager.xml
theme/theme/theme1.xml
theme/theme/_rels/themeManager.xml.rels

I was just thinking to add a code in demux_sample(filename, options) that will check filetype and if it is an office file then don't extract. maybe you have a better solution for this ;) Or if you want i can pull request my modification;)

Thanks;)

**Comment by brad-sp** [comment]
Are you sure you're using the latest version?  I'm not able to reproduce what you're describing with the sample you linked.  Our zip handling won't bother extracting files out of the zip unless they have some interesting extension or no extension (.xml, .rels are not either of these).

**Comment by mhanne0915** [comment]
my version is 5 days ago, i'll double check it again. It might be one of my modifications has messed up the zip handling. This will be closed for now. Thanks ;)
