### ISSUE TITLE
Problem with reporting TCP in network analysis

### ISSUE THREAD

**Issue by dforce** [brad-accuvant/cuckoo-modified#90]
I let my VM connect to the internet during analysis. I've set my network, in vm, to bridge connections with a static IP address (e.g. 172.16.30.100 and dns 172.16.30.1). The resultserver, running on host machine, set to IP address of host machine (e.g. 172.16.30.10).
Everything works fine but when I look at the results in network analysis, tcp connections, I see all the connections between my guest vm and host machine (like uploading python files to guest vm and sending results from guest to host machine).

Is this normal or what went or is set wrong on my side ?

Thanks

**Comment by dforce** [comment]
Problem solved.
There was a problem with my network settings. Changed them to host-only ad used iptables and everything is working fine now.

**Comment by dforce** [comment]
I want to reopen this issue because the problem isn't solved.
I can connect between host and guest, and connection fom the guest to the internet is working fine (followed the network seetings in cuckoosandbox documentation).The files are saved to the host.
When looking at the result of tcp network activity I see all the tcp connections between the guest and the host, like uploading the file, saving screenshots, saving files, creating logs etc.., thus everything that is saved s a results of the analysis.

Is someone having yhe same problem and how can ths be solved that only the real tcp connections are shown in the results, not the ones internaly between the guest and the host ?

Thanks

**Comment by dforce** [comment]
When I run the same file within the original cuckoosandbox, with the same settings in the different config files, everything runs fine. In the tcp section of network analysis I only see the real connections and not the connections between guest and host exchanging files and results.
Probably there is a little bug.

Can this be solved, because I ike using your modified version ?

Thanks

**Comment by brad-sp** [comment]
What do you have resultserver_port set to in the cuckoo.conf and the vm-specific .conf file?  What port is the resultserver actually running on?

**Comment by dforce** [comment]
in cuckoo.conf port is set to 2042 and in virtualbox.conf port is set to 3042 for those machine connecting to the internet. Other machines are using port 2042.
The resultserver, when running machines connecting to the internet, is using port 2042.

When I change back to sniffer.py from cuckoosandbox the problem is gone.

**Comment by brad-sp** [comment]
The port in your virtualbox.conf should be set to 2042 as well.  That should fix the issue.

**Comment by dforce** [comment]
This helps.
Thanks.
