### ISSUE TITLE
Too many dump files located on /tmp/ directory

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#99]
During network analysis, cuckoo creates /tmp/tmp\* file (e.g /tmp/tmpK_GJQ6) 
![tmp](https://cloud.githubusercontent.com/assets/10152712/8346899/c5625834-1b35-11e5-9754-04811699abb2.JPG)

**Comment by KillerInstinct** [comment]
These should be removed -- try adding some debug statements in this try/except:
https://github.com/brad-accuvant/cuckoo-modified/blob/1092fffb6e257e8a553c6420bfa49ca0bb7b2d6a/modules/processing/network.py#L734

eg

```
    finally:
        for chunk in chunks:
            try:
                chunk.close()
                os.remove(chunk.name)
            except Exception as e:
                log.warn(str(e))
```

I'm curious if we catch any information there.
